### ISSUE TITLE
How to send Program Change for Bank/Presets

### ISSUE THREAD

**Issue by devwmbr** [tttapa/Control-Surface#1]
How to send MIDI message with particular preset (bank) number? Let's assume we have buttons:  Bank Down, Bank Up. 
Bank Down sends decremented by -1 bank value and Bank Up sends incremented by +1 value. I would like to achieve solution for e.g. LED display which would display bank number and preset number.
Is possible and is there any sense?

![bank_and_presets](https://user-images.githubusercontent.com/32794257/32102415-7933740a-bb1c-11e7-89ad-b847a1dc92cf.PNG)

**Comment by tttapa** [comment]
Added it: https://github.com/tttapa/Control-Surface/commit/fadf0de8cd0f448e6f8a333731e50e5a02eee7dc
