### ISSUE TITLE
Teensy 4.0 and working project from PRO Micro

### ISSUE THREAD

**Issue by LukaszChrzanowski** [tttapa/Control-Surface#102]
Hello,

I've Teensy 4.0, and just uploaded code that worked on Arduino Pro Mini.
Board not registered as MIDI Device.

Should I change something in Arduino IDE options - like ex. USB Type?

**Comment by tttapa** [comment]
Yes, you have to select the MIDI USB Type for it to work. Be sure to use the latest version of Teensyduino.

**Comment by LukaszChrzanowski** [comment]
yeap.

works fine. Figured out myself but I sinked into greatness of Your's library :) (positive way of course).

Thread for close. :)
