### ISSUE TITLE
Button as a switch

### ISSUE THREAD

**Issue by kentforth** [tttapa/Control-Surface#104]
Hello Pieter!
**How can i use button as a toggle switch?**

I have two pin button. If I press once it sends midi cc with velocity 127, when I press it again it sends midi cc with velocity 0.

**Can you give me a simple sketch?**

**Comment by tttapa** [comment]
See https://github.com/tttapa/MIDI_controller/issues/104.

**Comment by kentforth** [comment]
Thank you!
