### ISSUE TITLE
Cannot set MIDI number for encoder

### ISSUE THREAD

**Issue by LukaszChrzanowski** [tttapa/Control-Surface#106]
I'vedefined Encoder:

```
CCRotaryEncoder enc = {
  {9, 10},       // pins
  {40, CHANNEL_1}, // MIDI address (CC number + optional channel)
  1,            // optional multiplier if the control isn't fast enough
};
```

but it seems that it occurs on 28 CHANNEL_1...
000018FE   1   2     B0    28    01    1  ---  Control Change
0000192D   1   2     B0    28    01    1  ---  Control Change
0000194C   1   2     B0    28    01    1  ---  Control Change
00001A07   1   2     B0    28    41    1  ---  Control Change
00001A27   1   2     B0    28    41    1  ---  Control Change

**Comment by tttapa** [comment]
The logs you posted are in hexadecimal. 2×16+8 = 40.

**Comment by LukaszChrzanowski** [comment]
in MIDI debug window it's 28... (DAW also say's it's 28)

**Comment by tttapa** [comment]
0x28 == 40

Most MIDI loggers show the data in hexadecimal.

If you want address hex 40, you have to use `0x40` in your code.

**Comment by LukaszChrzanowski** [comment]
yes - You are completly right. My lack of knowledge.

Thank You - thread for close
