### ISSUE TITLE
Setting the range of the pitch bend joystick

### ISSUE THREAD

**Issue by Wallirec** [tttapa/Control-Surface#1062]
Hello, thank you for the best midi library, I made several controllers that are ideal for me and that you can't buy in a store!
I assembled a pitch bend controller on the JoyStick Shield board (I bought three from different manufacturers), but the joystick gives out the final values ​​already at half the stroke. Please tell me how to set the extreme positions of the values ​​for the pitch bend?
![5282724339046800438](https://github.com/user-attachments/assets/7a2869d6-efce-4bfc-9e1a-90b67eb9f2b8)

**Comment by Wallirec** [comment]
the joystick removed from the board works well, it looks like the resistance curve in the shield changes

**Comment by josehdx** [comment]
hey collegue. can you share by change your example for the PB function?  you can check my repos, i am building a PB via BLE and i use a wig wag potentiometer (self return) but physically the are to big to fit on an already bought expression pedal case, so i am thinking to use these kind of joystick potentiometer, i just want to be sure about the deadzone solution implementation you have. please let me know!
