### ISSUE TITLE
Can I use mux for digital read of buttons?

### ISSUE THREAD

**Issue by maykefreitas** [tttapa/Control-Surface#12]

**Comment by tttapa** [comment]
Yes.

**Comment by maykefreitas** [comment]
@tttapa can you please give me an example of row to use `CD74HC4067` MUX with `CCButton`?

**Comment by tttapa** [comment]
Just like this example: <https://tttapa.github.io/Control-Surface/Doc/Doxygen/dd/dcc/md_Getting-Started.html>  
Then just pass the pin number to the CCButton contructor:
```cpp
CCButton button = {mux.pin(0), address};
```

**Comment by maykefreitas** [comment]
Thank you @tttapa, congratulations for the library. It's awesome. I turned a broken POD HD 500 into a MIDI controller with the Control Surface library. Just need to make expression pedal works, it's using an IR transmissor and receptor.

**Comment by tttapa** [comment]
Do you need help with the expression pedal? Do you have a picture, drawing or schematic?
