### ISSUE TITLE
Joystick invert midi cc value

### ISSUE THREAD

**Issue by kentforth** [tttapa/Control-Surface#126]
Hello Pieter!
I got a joystick module:

![joystick](https://user-images.githubusercontent.com/17134421/74831793-83ab1700-5348-11ea-99d9-3c4a141c63c4.jpg)

The problem is Joystick only have two pins. It's like I connect two potentiometers. But the value from them is reversed.

I assigned XPosition of Joystick  to channel volume of selected track in DAW and Y position to Pan of selected track. When I rotate joystick to right the channel volume goes left and vice versa

**How can I invert midi cc values from joystick for each individual pin of joystick?**
**Can you give me a simple sketch?**

This is my code:

```
#include <Control_Surface.h> // Include the Control Surface library

// Instantiate a MIDI over USB interface.
USBMIDI_Interface midi;

// Instantiate a CCButton object


CCPotentiometer volumePotentiometers[] = {
  {A0, { MIDI_CC::Channel_Volume, CHANNEL_1}}, //потенциометр подключен к пину А0, посылает MIDI CC с названием channel_volume, на  канал 1
  {A1, { MIDI_CC::Pan, CHANNEL_1}},
 
  };

void setup() {
  Control_Surface.begin(); // Initialize Control Surface
}

void loop() {
  Control_Surface.loop(); // Update the Control Surface
}
```

**Comment by tttapa** [comment]
You can use the [`CCPotentiometer::invert`](https://tttapa.github.io/Control-Surface-doc/Doxygen/db/d32/classCCPotentiometer.html#a7fa1616cc61c19a5efcc863c950f7f30) method.

To invert all potentiometers in the array:

```cpp
void setup() {
  for (auto &potentiometer : volumePotentiometers)
    potentiometer.invert();
  // ...
}
```

To invert a single potentiometer:
```cpp
void setup() {
  volumePotentiometers[0].invert();
  // ...
}
```

**Comment by kentforth** [comment]
Thank you!
