### ISSUE TITLE
Easy DIN5 MIDI to MIDI BLE on ESP32

### ISSUE THREAD

**Issue by fuegovic** [tttapa/Control-Surface#182]
***It was my mistake, see next comment for solution!***
 
B̵l̵u̵e̵t̵o̵o̵t̵h̵M̵I̵D̵I̵_̵I̵n̵t̵e̵r̵f̵a̵c̵e̵ ̵w̵o̵r̵k̵s̵ ̵b̵y̵ ̵i̵t̵s̵e̵l̵f̵ ̵b̵u̵t̵ ̵i̵f̵ ̵"̵U̵S̵B̵M̵I̵D̵I̵_̵I̵n̵t̵e̵r̵f̵a̵c̵e̵"̵ ̵o̵r̵ ̵"̵H̵a̵r̵d̵w̵a̵r̵e̵S̵e̵r̵i̵a̵l̵M̵I̵D̵I̵_̵I̵n̵t̵e̵r̵f̵a̵c̵e̵"̵ ̵i̵s̵ ̵a̵l̵s̵o̵ ̵p̵r̵e̵s̵e̵n̵t̵ ̵t̵h̵e̵ ̵B̵l̵u̵e̵t̵o̵o̵t̵h̵ ̵d̵e̵v̵i̵c̵e̵ ̵i̵s̵ ̵n̵o̵t̵ ̵d̵i̵s̵c̵o̵v̵e̵r̵a̵b̵l̵e̵ ̵a̵n̵y̵m̵o̵r̵e̵.̵ ̵(̵B̵L̵E̵ ̵s̵t̵o̵p̵p̵e̵d̵ ̵w̵o̵r̵k̵i̵n̵g̵)̵
̵
̵I̵ ̵d̵i̵s̵c̵o̵v̵e̵r̵e̵d̵ ̵t̵h̵e̵ ̵p̵r̵o̵b̵l̵e̵m̵ ̵w̵h̵i̵l̵e̵ ̵t̵r̵y̵i̵n̵g̵ ̵t̵o̵ ̵u̵s̵e̵ ̵t̵h̵e̵ ̵"̵M̵I̵D̵I̵_̵P̵i̵p̵e̵s̵-̵R̵o̵u̵t̵i̵n̵g̵"̵ ̵e̵x̵a̵m̵p̵l̵e̵.̵ ̵I̵ ̵m̵a̵d̵e̵ ̵s̵o̵m̵e̵ ̵t̵e̵s̵t̵s̵ ̵a̵n̵d̵ ̵q̵u̵i̵c̵k̵l̵y̵ ̵r̵e̵a̵l̵i̵z̵e̵ ̵t̵h̵a̵t̵ ̵t̵h̵e̵ ̵p̵r̵o̵b̵l̵e̵m̵ ̵w̵a̵s̵ ̵w̵i̵t̵h̵ ̵t̵h̵e̵ ̵o̵t̵h̵e̵r̵ ̵M̵I̵D̵I̵ ̵i̵n̵t̵e̵r̵f̵a̵c̵e̵s̵ ̵a̵n̵d̵ ̵n̵o̵t̵ ̵w̵i̵t̵h̵ ̵t̵h̵e̵ ̵r̵o̵u̵t̵i̵n̵g̵ ̵i̵t̵s̵e̵l̵f̵.̵ ̵

**Comment by fuegovic** [comment]
The error was in front of the monitor all along, I just had to redirect the HardwareSerialMIDI_Interface to "Serial" instead of "Serial1". 

Here's the code for the easiest way to make a DIN5 MIDI to MIDI BLE adapter!

Thanks, the library is amazing!

```
#include <Control_Surface.h>
#include <MIDI_Interfaces/BluetoothMIDI_Interface.hpp>

BluetoothMIDI_Interface MIDI_BLE;
HardwareSerialMIDI_Interface MIDI_SERIAL = Serial;

MIDI_PipeFactory<2> pipes;

void setup() {
  MIDI_BLE >> pipes >> MIDI_SERIAL; // all incoming midi from USB is sent to serial
  MIDI_BLE << pipes << MIDI_SERIAL; // all incoming midi from Serial is sent to USB

  MIDI_SERIAL.begin();
  MIDI_BLE.begin();
}

void loop() {
  MIDI_BLE.update();
  MIDI_SERIAL.update();
}
```

**Comment by tttapa** [comment]
Glad to hear you got it working!

**Comment by GiordanoSala** [comment]
is it possible to use Serial1 (RX2, TX2) ?
Everything works with DIN 5, 6N138 and an OLED for track names, when I transfer the program with HardwareSerialMIDI_Interface MIDI_SERIAL = Serial1;
The OLED screen just won't turn on.
All ok with Serial RX0, TX0.
