### ISSUE TITLE
BankSelector and 4067 multiplexer

### ISSUE THREAD

**Issue by santta** [tttapa/Control-Surface#184]
Hi, can I use in banks buttons connected through a 4067 multiplexer?  If can use, please give a link to an example.

**Comment by tttapa** [comment]
Yes, you can use it in exactly the same way as with other pins. Just supply `yourMultiplexer.pin(0)` as the pin argument to the bank selector constructor.

**Comment by santta** [comment]
![ScreenShot_20200427112536](https://user-images.githubusercontent.com/45362973/80350804-ee615d00-8879-11ea-82eb-0f1642669865.png)

If in the test assembly I have 4 buttons for the bank selector ( connected to the arduino pins), and 4 LED 
for indication (connected to the arduino pins). 
Each of the selector buttons changes to a specific channel for all controller elements.

Also connected to my controller:
4 encoders, via Arduino pins. 
4 buttons via Mux4067

What an example sketch might look like?

![ScreenShot_20200427110012](https://user-images.githubusercontent.com/45362973/80348334-50b85e80-8876-11ea-8058-20b78e40fb08.png)

**Comment by tttapa** [comment]
What have you tried? You'll probably need the ManyButtonsSelectorLEDs class: https://tttapa.github.io/Control-Surface-doc/Doxygen/d0/d68/classManyButtonsSelectorLEDs.html

**Comment by santta** [comment]
I already use ManyButtonsSelectorLEDs (https://github.com/tttapa/Control-Surface/issues/136) - this is a great selector.
I continue to study your Surface library. And now I'm looking for a way to change the channels sent by Midi CC with this selector

**Comment by santta** [comment]
thanks, I was able to make a working sketch


    #include <Encoder.h>
    #include <Control_Surface.h> // Подключение библиотеки
    USBMIDI_Interface midi; // Подключение USB интерфейса


    Bank<4> bank(1);
    ManyButtonsSelectorLEDs<4> bankselector = {
    bank,
    {6, 7, 8, 9}, // button pins
    {10, 11, 12, 13}, // led pins
    };


     Bankable::CCRotaryEncoder enc[] = {
     {{bank, BankType::CHANGE_CHANNEL}, {2, 3}, 0x08, 1, 4},
     };

    CD74HC4067 mux2 = {A5,{A1, A2, A3, A4} };
    Bankable::CCButton button1[] = {
    {{bank, BankType::CHANGE_CHANNEL},  mux2.pin(1), { 0x0E, CHANNEL_1 } },
    };

    Bankable::CCButton butt[] = {
    {{bank, BankType::CHANGE_CHANNEL}, 4, {0x08, CHANNEL_2} }, // 
     };

      void setup() {
     Control_Surface.begin(); // Initialize Control Surface
     }

      void loop() {
      Control_Surface.loop(); // Update the Control Surface
      }

**Comment by santta** [comment]
Pieter, thanks for your wonderful library, I enjoy using it.  Perhaps you see errors in my sketch or improvements to improve the sketch?

**Comment by tttapa** [comment]
Thanks for sharing your code, it looks alright at first sight.
