### ISSUE TITLE
ESP32 issue

### ISSUE THREAD

**Issue by Sixonlon** [tttapa/Control-Surface#186]
I tried your examples on a DOIT ESP32 Devkit V1 but it seems that it is not supported. I don't even achieve to compile the example. I tried the OLED-display ones but also the ones in the folder esp32 but none of them compile. Is it due to your current changes and updates or it comes from else where ?

The error is simply : compiling error for the board DOIT ESP32 DevKit V1.

Thanks in advence !

Simon

**Comment by tttapa** [comment]
Could you post the full error message? The [CI tests](https://travis-ci.org/github/tttapa/Control-Surface) seem to compile just fine, so I assume there's either a problem with the specific version of the ESP32 Arduino Core you're using, or with the Core configuration of your specific board (the CI tests use the SparkFun ESP32 Thing, IIRC).

I'll see if I can reproduce this problem later today.

**Comment by Sixonlon** [comment]
Here is the full message error : 

In file included from C:\Users\Portable\Documents\Arduino\libraries\Encoder/Encoder.h:46:0,

                 from C:\Users\Portable\Documents\Arduino\libraries\Control-Surface-master\src\MIDI_Outputs\ManyAddresses\CCRotaryEncoder.cpp:1:

C:\Users\Portable\Documents\Arduino\libraries\Encoder/utility/interrupt_pins.h:202:2: error: #error "Interrupts are unknown for this board, please add to this code"

 #error "Interrupts are unknown for this board, please add to this code"

  ^

C:\Users\Portable\Documents\Arduino\libraries\Encoder/utility/interrupt_pins.h:205:2: error: #error "Encoder requires interrupt pins, but this board does not have any :("

 #error "Encoder requires interrupt pins, but this board does not have any :("

  ^

C:\Users\Portable\Documents\Arduino\libraries\Encoder/utility/interrupt_pins.h:206:2: error: #error "You could try defining ENCODER_DO_NOT_USE_INTERRUPTS as a kludge."

 #error "You could try defining ENCODER_DO_NOT_USE_INTERRUPTS as a kludge."

  ^

In file included from C:\Users\Portable\Documents\Arduino\libraries\Control-Surface-master\src\MIDI_Outputs\ManyAddresses\CCRotaryEncoder.cpp:1:0:

C:\Users\Portable\Documents\Arduino\libraries\Encoder/Encoder.h:61:11: error: 'IO_REG_TYPE' does not name a type

  volatile IO_REG_TYPE * pin1_register;

           ^

C:\Users\Portable\Documents\Arduino\libraries\Encoder/Encoder.h:62:11: error: 'IO_REG_TYPE' does not name a type

  volatile IO_REG_TYPE * pin2_register;

           ^

C:\Users\Portable\Documents\Arduino\libraries\Encoder/Encoder.h:63:2: error: 'IO_REG_TYPE' does not name a type

  IO_REG_TYPE            pin1_bitmask;

  ^

C:\Users\Portable\Documents\Arduino\libraries\Encoder/Encoder.h:64:2: error: 'IO_REG_TYPE' does not name a type

  IO_REG_TYPE            pin2_bitmask;

  ^

In file included from C:\Users\Portable\Documents\Arduino\libraries\Control-Surface-master\src\MIDI_Outputs\ManyAddresses\CCRotaryEncoder.cpp:1:0:

C:\Users\Portable\Documents\Arduino\libraries\Encoder/Encoder.h:45:30: error: 'CORE_NUM_INTERRUPT' was not declared in this scope

 #define ENCODER_ARGLIST_SIZE CORE_NUM_INTERRUPT

                              ^

C:\Users\Portable\Documents\Arduino\libraries\Encoder/Encoder.h:135:50: note: in expansion of macro 'ENCODER_ARGLIST_SIZE'

  static Encoder_internal_state_t * interruptArgs[ENCODER_ARGLIST_SIZE];

                                                  ^

In file included from C:\Users\Portable\Documents\Arduino\libraries\Control-Surface-master\src\MIDI_Outputs\ManyAddresses\CCRotaryEncoder.cpp:1:0:

C:\Users\Portable\Documents\Arduino\libraries\Encoder/Encoder.h: In constructor 'Encoder::Encoder(uint8_t, uint8_t)':

C:\Users\Portable\Documents\Arduino\libraries\Encoder/Encoder.h:82:11: error: 'struct Encoder_internal_state_t' has no member named 'pin1_register'

   encoder.pin1_register = PIN_TO_BASEREG(pin1);

           ^

C:\Users\Portable\Documents\Arduino\libraries\Encoder/Encoder.h:82:46: error: 'PIN_TO_BASEREG' was not declared in this scope

   encoder.pin1_register = PIN_TO_BASEREG(pin1);

                                              ^

C:\Users\Portable\Documents\Arduino\libraries\Encoder/Encoder.h:83:11: error: 'struct Encoder_internal_state_t' has no member named 'pin1_bitmask'

   encoder.pin1_bitmask = PIN_TO_BITMASK(pin1);

           ^

C:\Users\Portable\Documents\Arduino\libraries\Encoder/Encoder.h:83:45: error: 'PIN_TO_BITMASK' was not declared in this scope

   encoder.pin1_bitmask = PIN_TO_BITMASK(pin1);

                                             ^

C:\Users\Portable\Documents\Arduino\libraries\Encoder/Encoder.h:84:11: error: 'struct Encoder_internal_state_t' has no member named 'pin2_register'

   encoder.pin2_register = PIN_TO_BASEREG(pin2);

           ^

C:\Users\Portable\Documents\Arduino\libraries\Encoder/Encoder.h:85:11: error: 'struct Encoder_internal_state_t' has no member named 'pin2_bitmask'

   encoder.pin2_bitmask = PIN_TO_BITMASK(pin2);

           ^

C:\Users\Portable\Documents\Arduino\libraries\Encoder/Encoder.h:92:31: error: 'struct Encoder_internal_state_t' has no member named 'pin1_register'

   if (DIRECT_PIN_READ(encoder.pin1_register, encoder.pin1_bitmask)) s |= 1;

                               ^

C:\Users\Portable\Documents\Arduino\libraries\Encoder/Encoder.h:92:54: error: 'struct Encoder_internal_state_t' has no member named 'pin1_bitmask'

   if (DIRECT_PIN_READ(encoder.pin1_register, encoder.pin1_bitmask)) s |= 1;

                                                      ^

C:\Users\Portable\Documents\Arduino\libraries\Encoder/Encoder.h:92:66: error: 'DIRECT_PIN_READ' was not declared in this scope

   if (DIRECT_PIN_READ(encoder.pin1_register, encoder.pin1_bitmask)) s |= 1;

                                                                  ^

C:\Users\Portable\Documents\Arduino\libraries\Encoder/Encoder.h:93:31: error: 'struct Encoder_internal_state_t' has no member named 'pin2_register'

   if (DIRECT_PIN_READ(encoder.pin2_register, encoder.pin2_bitmask)) s |= 2;

                               ^

C:\Users\Portable\Documents\Arduino\libraries\Encoder/Encoder.h:93:54: error: 'struct Encoder_internal_state_t' has no member named 'pin2_bitmask'

   if (DIRECT_PIN_READ(encoder.pin2_register, encoder.pin2_bitmask)) s |= 2;

                                                      ^

C:\Users\Portable\Documents\Arduino\libraries\Encoder/Encoder.h:93:66: error: 'DIRECT_PIN_READ' was not declared in this scope

   if (DIRECT_PIN_READ(encoder.pin2_register, encoder.pin2_bitmask)) s |= 2;

                                                                  ^

C:\Users\Portable\Documents\Arduino\libraries\Encoder/Encoder.h: In static member function 'static void Encoder::update(Encoder_internal_state_t*)':

C:\Users\Portable\Documents\Arduino\libraries\Encoder/Encoder.h:274:40: error: 'struct Encoder_internal_state_t' has no member named 'pin1_register'

   uint8_t p1val = DIRECT_PIN_READ(arg->pin1_register, arg->pin1_bitmask);

                                        ^

C:\Users\Portable\Documents\Arduino\libraries\Encoder/Encoder.h:274:60: error: 'struct Encoder_internal_state_t' has no member named 'pin1_bitmask'

   uint8_t p1val = DIRECT_PIN_READ(arg->pin1_register, arg->pin1_bitmask);

                                                            ^

C:\Users\Portable\Documents\Arduino\libraries\Encoder/Encoder.h:274:72: error: 'DIRECT_PIN_READ' was not declared in this scope

   uint8_t p1val = DIRECT_PIN_READ(arg->pin1_register, arg->pin1_bitmask);

                                                                        ^

C:\Users\Portable\Documents\Arduino\libraries\Encoder/Encoder.h:275:40: error: 'struct Encoder_internal_state_t' has no member named 'pin2_register'

   uint8_t p2val = DIRECT_PIN_READ(arg->pin2_register, arg->pin2_bitmask);

                                        ^

C:\Users\Portable\Documents\Arduino\libraries\Encoder/Encoder.h:275:60: error: 'struct Encoder_internal_state_t' has no member named 'pin2_bitmask'

   uint8_t p2val = DIRECT_PIN_READ(arg->pin2_register, arg->pin2_bitmask);

                                                            ^

**Comment by tttapa** [comment]
You seem to be using an outdated version of the PJRC Encoder library that doesn't support the ESP32 yet.

Please try upgrading to the latest version from GitHub: https://github.com/PaulStoffregen/Encoder

**Comment by Sixonlon** [comment]
Indeed, it works now.

Thanks a lot !
