### ISSUE TITLE
Analog ButtonKeypad module (3pins)

### ISSUE THREAD

**Issue by santta** [tttapa/Control-Surface#193]
![httprobotdyn compubmedia0g-00004912mod-buttonkeypad4x4photophotoangle0g-00004912mod-buttonkeypad4x4assembled](https://user-images.githubusercontent.com/45362973/80949500-d13e0880-8dfc-11ea-84e3-5f9d0610cf7d.jpg)
Hi, Pieter, do you have any connection experiments for the Analog ButtonKeypad module?

This module is different from the matrix of buttons from the examples in your library, but it only connects with 3 pins. (VCC, GND, analog pin)

Pressing one of the buttons SW1-SW16 forms a voltage divider at the output 1 (Out), and each button has its own unique voltage divider. For example, for the SW2 button - 1/10, for the SW10 button - 11/10. By connecting this contact to the analog input of the microcontroller, when the buttons are pressed, we will get different values by which we can identify the pressed button.

P.S. using such a module would be a great alternative to connecting buttons for mux4067
![PINOUT==0G-00004912==Mod-ButtonKeypad4x4](https://user-images.githubusercontent.com/45362973/80949550-e3b84200-8dfc-11ea-9b16-e91638300fe3.jpg)
![ScreenShot_20200504114147](https://user-images.githubusercontent.com/45362973/80949558-e74bc900-8dfc-11ea-8b0e-e9f6da33db68.png)

     void setup() {
     // selial port initialization
      Serial.begin(9600);
    }

    void loop() {
    // get value of A1 analog input
    int valueA1=analogRead(A1);
    // output data to serial port
    Serial.println(valueA1);
    // pause
    delay(500);
   }

![httprobotdyn compubmedia0g-00004912mod-buttonkeypad4x4photophotobottom0g-00004912mod-buttonkeypad4ex4assembled](https://user-images.githubusercontent.com/45362973/80950869-63dfa700-8dff-11ea-8f98-2e327b0454e6.jpg)

![H2824a5068f804401aa61db34a67a4dccE](https://user-images.githubusercontent.com/45362973/80949566-eadf5000-8dfc-11ea-954b-a566d885e046.jpg)
![Schematic==0G-00004912==Mod-ButtonKeypad4x4](https://user-images.githubusercontent.com/45362973/80949570-eca91380-8dfc-11ea-9d54-22fa2e4cddc5.jpg)

**Comment by tttapa** [comment]
I've never tried anything like that, but it shouldn't be too hard to implement it yourself: https://tttapa.github.io/Control-Surface-doc/Doxygen/d4/d3b/Custom-MIDI-Output-Element_8ino-example.html
