### ISSUE TITLE
Add AppleMIDI native interface

### ISSUE THREAD

**Issue by djoulz22** [tttapa/Control-Surface#194]
It's note an issue but a request to add AppleMIDI native interface.

Thanks and good job!

**Comment by tttapa** [comment]
AppleMIDI support was added in #196, you can find an example here: [AppleMIDI.ino](https://tttapa.github.io/Control-Surface-doc/Doxygen/dc/d7d/AppleMIDI_8ino-example.html)

**Comment by djoulz22** [comment]
Hi,

Great, U R a Dev Killer!

Thanks for the functionnality, I will try it

Bye
