### ISSUE TITLE
Potentiometer Calibrated? Need Help

### ISSUE THREAD

**Issue by LuckyMann** [tttapa/Control-Surface#21]
There is a example for Potentiometer map Calibrated like the old version? im trying :

```cpp
CCPotentiometer potentiometer(A15, {MIDI_CC::Channel_Volume, CHANNEL_2});

const int minimumValue = 10;    // the analog value read when the potentiometer is in the minimum position.
const int maximumValue = 1000; // the analog value read when the potentiometer is in the maximum position.

int mapCalibrated(int value) {
  value = constrain(value, minimumValue, maximumValue); // make sure that the analog value is between the minimum and maximum value
  return map(value, minimumValue, maximumValue, 0, 1023); // map the value from [minimumValue, maximumValue] to [0, 1023]
}
```
but doesnt work
Thank you

**Comment by tttapa** [comment]
I added an example here: <https://tttapa.github.io/Control-Surface/Doc/Doxygen/d3/d26/CCPotentiometer-Map_8ino-example.html>

**Comment by LuckyMann** [comment]
Thank You, I'll try it.

**Comment by LuckyMann** [comment]
Its working. but unfortunately I didnt get smooth result like the old Libraries. So Im Back to the old one. Thanks anyway.

**Comment by tttapa** [comment]
Could you post your mapping function?

The difference with the old one is that the new one reduces the bit depth first, before applying the mapping function. This reduces the amount of noise, but comes at a cost of losing bit depth for the mapping.  
Do you get a lot of noise with the old code, or is it not an issue? If not, I might change it back in the new library.

**Comment by LuckyMann** [comment]
I do exactly as the example method. And the “get raw value” doesnt work too. Or maybe just me. 

I dont know about the others, but I feel getting best smooth callibration result when using the old library.
