### ISSUE TITLE
Increment y decrement en pin analogico

### ISSUE THREAD

**Issue by alomdj00** [tttapa/Control-Surface#217]
Hola, quisiera saber si es posible reemplazar los dos pines de CCIncrementDecrementButtons por un pin analogico y que cumpla la misma funcion. Digamos que cuando la lectura analogica sea menor que 40 disminuya el valor y si es mas de 80 suba el valor al igual que lo hace CCIncrementDecrementButtons, esto a fin de usar un motor con operacionales asi la salida del opamp se mantendra en 2.5v y segun el sentido en que gire subira o bajara de voltaje.
Estuve tratando de crear dichafuncion pero me tira error al compilar no se a que se deba, si pudieses orientarme un poco te lo agradeceria. Dejo el codigo que tengo asta el momento.

`
#include <Control_Surface.h> 

USBMIDI_Interface midi;

#pragma once

#include <AH/Hardware/IncrementDecrementButtons.hpp>
#include <Def/Def.hpp>
#include <MIDI_Outputs/Abstract/MIDIOutputElement.hpp>

#include <MIDI_Senders/DigitalNoteSender.hpp>

BEGIN_CS_NAMESPACE

/**
 * @brief   An abstract class for two buttons that send incremental MIDI events.
 */
template <class RelativeSender, class ResetSender>
class incdecanalog : public MIDIOutputElement {
  protected:
    /**
     * @brief   Construct a new MIDIIncrementDecrementButtons.
     *
     * @todo    Documentation
     */
    incdecanalog( AH::FilteredAnalog<7> &analog,
                                  const MIDIAddress &address,
                                  uint8_t multiplier,
                                  const MIDIAddress &resetAddress,
                                  const RelativeSender &relativeSender,
                                  const ResetSender &resetSender)
        : analog(analog), address(address), multiplier(multiplier),
          resetAddress(resetAddress), relativeSender(relativeSender),
          resetSender(resetSender) {}

  public:
void begin() override {  }

void update() override {
    (analog.update());
    uint8_t analo = analog.getValue();
    if (analo<=40) {send(multiplier, address);}
    if (analo>=80) {send(-multiplier, address);}

    }

    void send(long delta, const MIDIAddress &address) {
        relativeSender.send(delta, address);
    }

    void reset() {
        if (resetAddress) {
            resetSender.sendOn(resetAddress);
            resetSender.sendOff(resetAddress);
        }
    }

#ifdef AH_INDIVIDUAL_BUTTON_INVERT
    void invert() { analog.invert(); }
#endif

  private:
  AH::FilteredAnalog<7> analog; 
    const MIDIAddress address;
    const uint8_t multiplier;
    const MIDIAddress resetAddress;

  public:
    RelativeSender relativeSender;
    ResetSender resetSender;
};

END_CS_NAMESPACE

incdecanalog buttons = {   //  error: invalid use of template-name 'CS::incdecanalog' without an argument list
    {A0},              // Button pins: 5 increments, 6 decrements
    MCU::V_POT_1,        // Increment/Decrement CC address
    1,                   // Multiplier
    MCU::V_POT_SELECT_1, // Reset note address
};

void setup() {
  Control_Surface.begin(); // Initialize Control Surface
  // No need to initialize the MAX7219 or to set pinModes, all of this
  // is handled by Control Surface.
}

void loop() {
  Control_Surface.loop(); // Update the Control Surface
}

` 
[increment_decrement_analog.zip](https://github.com/tttapa/Control-Surface/files/4773718/increment_decrement_analog.zip)

**Comment by tttapa** [comment]
I see you closed this issue. Did you get it working or do you need help with it?
