### ISSUE TITLE
Unable to use relative rotary encoder

### ISSUE THREAD

**Issue by SwooshMihu** [tttapa/Control-Surface#218]
I am trying to create a custom MIDI controller that i will use in conjuction with MIDI2LR(https://github.com/rsjaffe/MIDI2LR) to create a physical interface with Adobe Lightroom. Right now i am trying to set up a rotary encoder to use as an alternative to a potentiometer and i am having some difficulties with it. I am trying to define the encoder as being relative, using the RotaryEncoder.ino program( i have tried using  RelativeCCSender::setMode(relativeCCmode::MACKIE_CONTROL_RELATIVE); 
as well as
RelativeCCSender::setMode(relativeCCmode::TWOS_COMPLEMENT);
and i get no output whatsoever, neither in MIDI-OX, nor in MIDI2LR.

If i use the  AbsoluteRotaryEncoder.ino program, instantiating the encoder as a CCAbsoluteEncoder
i still get no output but if i instantiate it as PBAbsoluteEncoder, i do get the following output in MIDI-OX:
![image](https://user-images.githubusercontent.com/47503915/84601168-04a59580-ae87-11ea-9f54-6b2b68f83462.png)
The program used:
#include <Encoder.h> // Include the Encoder library.
#include <Control_Surface.h> // Include the Control Surface library
USBMIDI_Interface midi;
// Similarly, for Pitch Bend
    PBAbsoluteEncoder enc = {
      {2, 3},    // pins
      CHANNEL_1, // MIDI channel
      127,       // large multiplier because Pitch Bend has high resolution
    };
void setup() {
  Control_Surface.begin(); // Initialize Control Surface
}
void loop() {
  Control_Surface.loop(); // Update the Control Surface
}

The rotary encoder that i am using is this : https://www.tme.eu/ro/en/details/ps1010-20/rotary-switches/ctr/ps1010-20-kq15a6-0-000/ , wired according to their diagram.

**Comment by tttapa** [comment]
The MIDI-OX screenshot makes me believe you wired the rotary encoder incorrectly.  
From what I can gather on the product page, you have to wire pins 1 and 4 of the encoder to ground, and pins 2 and 3 to pins 2 and 3 of the Arduino.

**Comment by SwooshMihu** [comment]
After rewiring, this is the result i get using PitchBend
![image](https://user-images.githubusercontent.com/47503915/84643977-34947d80-af07-11ea-9987-48542b9abe65.png)
Yet no output can be seen when instantiating the encoder as CCAbsoluteEncoder nor as CCRotaryEncoder

**Comment by tttapa** [comment]
You could try using the Encoder library directly, it'll be easier to debug: https://github.com/PaulStoffregen/Encoder/blob/master/examples/Basic/Basic.pde 

I'm pretty sure that this is a hardware problem rather than an issue with the libraries involved.

**Comment by SwooshMihu** [comment]
Right, using the encoder library directly i can see this on the serial output so i guess it's working fine?
![image](https://user-images.githubusercontent.com/47503915/84647924-cfdc2180-af0c-11ea-9275-2f8e63cb5f81.png)
Yet i get no output from it in MIDI-OX, nor in MIDI2LR

**Comment by tttapa** [comment]
No, that's not fine, when you turn the encoder, you should see the position printed, not just -1, 0 and 1. Please post your exact wiring diagram and a picture of the wiring.

**Comment by SwooshMihu** [comment]
This is the wiring that i have used to get the -1, 0, 1 result 
![image](https://user-images.githubusercontent.com/47503915/84702002-a3e98c00-af5e-11ea-81f3-88e74f8b8a29.png)
I do not have a multimeter right now to test if the connections are ok. I will also get an EC11 encoder to test that one aswell.

**Comment by SwooshMihu** [comment]
I have simply ditched that encoder and picked up a new one with this wiring 
![image](https://user-images.githubusercontent.com/47503915/85126737-be5d8700-b236-11ea-946a-ba2dda10ead0.png)
and it works without problems. thanks for your time
