### ISSUE TITLE
chords with note button and mix

### ISSUE THREAD

**Issue by benwadub** [tttapa/Control-Surface#222]
hi, i plan to make a small midi keyboard with your library, can you tell me if I ll be able to play chords with my buttons wired through 4067 mux?
does it allow to play more than one note at the same time or would it be better to use matrix button or something else?

**Comment by tttapa** [comment]
Yes, a mux will allow you to register multiple key presses at once.

**Comment by benwadub** [comment]
Thanks!
I ll go for that solution!
