### ISSUE TITLE
Problem Using Serial Monitor

### ISSUE THREAD

**Issue by mipabersatu** [tttapa/Control-Surface#247]
So I'm trying to monitor the value of potentiometer in the serial monitor. But it happens that the monitor won't appear when I clicked it. 
Do you know what possibly can affect it?

**Comment by tttapa** [comment]
This sounds like an issue with your installation of the Arduino IDE, not with the Control Surface library.

**Comment by mipabersatu** [comment]
But I tried a regular code just to show serials on monitor and it did work.

**Comment by tttapa** [comment]
Does the monitor not appear, or does it not print to the monitor?

**Comment by mipabersatu** [comment]
The monitor appear once and it doesn't print.

**Comment by tttapa** [comment]
Then you'll have to post the code you're using.

**Comment by mipabersatu** [comment]
Oh I found the problem and you're right it's because of the outdated IDE I guess. I updated the program and it fixed. Thanks.
