### ISSUE TITLE
How to set maximum midi cc for potentiometer when pot is turned on half position?

### ISSUE THREAD

**Issue by kentforth** [tttapa/Control-Surface#260]
When I turn a potentiometer on 13:00 o clock I want a pot to send it's maximum value of midi cc(127) 
**How can I do that?**

Can you show me the code where I can change it?

**Comment by tttapa** [comment]
You can do this by changing the maximum value in this example: https://tttapa.github.io/Control-Surface-doc/Doxygen/d3/d26/CCPotentiometer-Map_8ino-example.html

**Comment by kentforth** [comment]
Thank you so much!
