### ISSUE TITLE
MIDI IN / LED with multiplexer ?

### ISSUE THREAD

**Issue by brian12112** [tttapa/Control-Surface#3]
I know this library is under construction, but my questions is  there is a way or did it support using Multiplexer for MIDI Input / LEDs for the Final/Alpha Release? Maybe an example?

Thank You

**Comment by brian12112** [comment]
Wow, Its a great news. This is I be waiting for.  Thank you tttapa.

**Comment by tttapa** [comment]
Note that you don't have to use RGB LEDs, you can use ordinary LEDs as well, and you can use any number of shift registers.  

For example, if you want a single shift register with 8 normal LEDs:
```cpp
 ShiftRegisterOut ShiftReg(dataPin, clockPin, latchPin, LSBFIRST, 8); 
  
 MIDI_LED leds[] = { 
   {ShiftReg.pin(0), MCU::MUTE_1, channel}, 
   {ShiftReg.pin(1), MCU::MUTE_2, channel}, 
   {ShiftReg.pin(2), MCU::MUTE_3, channel}, 
   {ShiftReg.pin(3), MCU::MUTE_4, channel}, 
   {ShiftReg.pin(4), MCU::MUTE_5, channel}, 
   {ShiftReg.pin(5), MCU::MUTE_6, channel}, 
   {ShiftReg.pin(6), MCU::MUTE_7, channel}, 
   {ShiftReg.pin(7), MCU::MUTE_8, channel},  
 }; 
```

**Comment by brian12112** [comment]
Wow, I am consider to using it with Standalone LEDs. Thank You again tttapa. It helps me a lot!

**Comment by brian12112** [comment]
Just one last questions. There is a solution to using multiplexer or shift register for the buttons? Thanks B4!

**Comment by tttapa** [comment]
You can use `AnalogMultiplex` for buttons as well.
Or you can use a button matrix.

**Comment by brian12112** [comment]
Thanks. I'll give it a try.
