### ISSUE TITLE
Shift Registers with leds

### ISSUE THREAD

**Issue by kentforth** [tttapa/Control-Surface#32]
Hi Pieter!
I want to use shift register 74HC595 to connect 8 leds to Arduino Leonardo. I saw your example TOGGLE LEDs, but I didn't find line with code where you define Arduino pins for connecting shift registers. Shift register require 3 pins for communication with Arduino(latch pin, data pin and clock pin) I just can't find where you define it.

May be there is some file in your library where you did it?

Can you explain this to me?

**Comment by kentforth** [comment]
The problem is I don't understand what pins on Arduino are MOSI, CLK and SS?  if I replace SS by any digital arduino pins like that:
SPIShiftRegisterOut<mux.length()> sreg = {10, MSBFIRST};

What about other pins MOSI and CLK? Where should I connect that pins on Leonardo?

**Comment by tttapa** [comment]
The SPI pins are on the ICSP header.

![](https://www.theengineeringprojects.com/wp-content/uploads/2018/10/introduction-to-arduino-leonardo-2-2.png)

**Comment by kentforth** [comment]
I found only MOSI pin here. Can you highlight other 2 pins?
Can SS pin be any digital pin on arduino?

**Comment by tttapa** [comment]
CLK (clock) and SCK (serial clock) are the same. In master mode (which is what you use for shift registers), SS can be any digital pin.

**Comment by kentforth** [comment]
Am I right?

![leonardo](https://user-images.githubusercontent.com/17134421/63573201-f06a7200-c5ae-11e9-966a-35819420bbf7.jpg)

**Comment by tttapa** [comment]
I think CLK is the top one in the middle, not the right one.

And SS can be any pin, as long as you change it in the code. Pin 10 is a popular choice, because it's the SS pin of the Arduino UNO.

**Comment by kentforth** [comment]
Thanx for your answer.
I appreciate your work! I will close issue

**Comment by tttapa** [comment]
Glad to hear :)
