### ISSUE TITLE
Implementation of SPDT Switch

### ISSUE THREAD

**Issue by kentforth** [tttapa/Control-Surface#331]
Is there any implementation in the library for switches like SPDT?
For example:
 I switch to one position: -> midi CC 80 is ON
I switch to another position -> midi CC 80 is OFF
**Can you give me an example?**

![1](https://user-images.githubusercontent.com/17134421/99150355-97f92600-26c6-11eb-9a01-52133cb55184.jpg)

**Comment by tttapa** [comment]
You can just use the standard `CCButton` class for this.

**Comment by kentforth** [comment]
You have CCButtonLatched class, is that best to use it?

**Comment by tttapa** [comment]
> You have CCButtonLatched class, is that best to use it?

No, `CCButtonLatched` latches the input in software, which is not what your example did.

**Comment by kentforth** [comment]
Thank you!
