### ISSUE TITLE
How to use Midi CC instead of Note with button?

### ISSUE THREAD

**Issue by kentforth** [tttapa/Control-Surface#34]
Hi Pieter!
I want to use button and send midi cc, but in your example : Midi Output/Buttons and Switched/Momentary push buttons/NoteButton you made sending only NoteNumber

**How can I change the code to send Midi CC to my DAW instead of NoteNumber with a button?**

**Can you give me a nexample of using a button that sends midi cc?**

**Comment by tttapa** [comment]
You can find an overview of all MIDI elements in the documentation:  
https://tttapa.github.io/Control-Surface/Doc/Doxygen/d7/dcd/group__MIDIOutputElements.html

You can use `CCButton` instead of `NoteButton`.

**Comment by kentforth** [comment]
I didn't find an example for button that sends MIDI CC instead of Midi Note, can you show a simple sketch where pressing a button will send midi cc?

**Comment by tttapa** [comment]
I added an example: https://tttapa.github.io/Control-Surface/Doc/Doxygen/d9/d2e/CCButton_8ino-example.html

**Comment by kentforth** [comment]
Thank you!
