### ISSUE TITLE
Add "seven segment led display"

### ISSUE THREAD

**Issue by santta** [tttapa/Control-Surface#340]
hello, Pieter, how add "seven segment led display" to indicate the number "IncrementDecrementSelector"?
![HTB1V0iuayfrK1RjSspbq6A4pFXaE](https://user-images.githubusercontent.com/45362973/100007183-bfde3d00-2ddc-11eb-82ac-4c3ac0e174f6.jpg)
![working-with-seven-segment-displays-fig1](https://user-images.githubusercontent.com/45362973/100007185-c10f6a00-2ddc-11eb-9ac4-863ec7e6e822.jpg)

**Comment by tttapa** [comment]
This is currently not supported by Control Surface, but it's easy enough to program yourself, independently from Control Surface. You can get the current selection from the selector using the `IncrementDecrementSelector::get()` method.

**Comment by santta** [comment]
Thanks for the answer, I will try it, then I will definitely share the sketch.
