### ISSUE TITLE
botton bank

### ISSUE THREAD

**Issue by zley1** [tttapa/Control-Surface#38]
hi, i am having trouble on a code for a 6 banks of buttonmatrix with 6 leds and two butons for changing banks
buttom matrix is 6 buttons (two rows 3 colums)
i want to be able to choose the note for each button in every bank. i try some of the examples but i get errors with them.
thanks in advance

**Comment by tttapa** [comment]
I added an example, but I haven't tested it yet.

**Comment by zley1** [comment]
thnx!! but how do i choose the notes for each bank? i want to have different scales for playing melodies.

**Comment by zley1** [comment]
thnx!! but how do i choose the notes for each bank? i want to have different scales for playing melodies.

**Comment by tttapa** [comment]
That's currently not supported. But I'm in the process of adding the code for it.

**Comment by zley1** [comment]
ok thnx!! let me know if u make it.

**Comment by tttapa** [comment]
I added [NoteButtonMatrix](https://tttapa.github.io/Control-Surface/Doc/Doxygen/d3/d39/classBankable_1_1ManyAddresses_1_1NoteButtonMatrix.html), but I don't have time at the moment to add the LEDs.

**Comment by panakronic** [comment]
Hi 

I have 4 banks with two butons for changing banks. Please see example MIDI_controller-97.

My question: Is is possible to use RGB LED strip with 4 pre-defined colors instead of 4 seperate LED of different color? I am currently using a 5mm 4-pin RGB LED bulb and it allows me only 3 color changes - Red, Green and Blue. How can I add one or more colors?

**Comment by tttapa** [comment]
The LED outputs for the Selectors are defined herehttps://github.com/tttapa/Control-Surface/blob/aa4086fe1c93ba66bf510fef3485a82a0e5202ef/src/Selectors/LEDs/SelectorLEDs.hpp#L9-L33

You can easily write your own callback to drive the LEDs the way you want. Then you just pass your callback class to the Generic***Selector template classes, as shown in further down in the file mentioned earlier.
