### ISSUE TITLE
How to connect multiple multiplexers and buttons?

### ISSUE THREAD

**Issue by kentforth** [tttapa/Control-Surface#54]
Hello Pieter!
I use Multiplexers 4067
I saw your example with multiplexer and button but what if I wanna use multiple multiplexers and many buttons that send midi notes

**How should I connect pins of all multiplexers? I mean pins SIG, S0, S1, S2, S3**

**What code for multiplexers should look like? Can you give me an example?**

**Comment by tttapa** [comment]
Did you see this? https://tttapa.github.io/Control-Surface/Doc/Doxygen/dd/dcc/md_Getting-Started.html#first-output-extio

Each multiplexer should have its own signal pin, the address select lines can be shared.

**Comment by kentforth** [comment]
Thanx!
