### ISSUE TITLE
 how to use two or three or more than Multiplexers 4067 to expand the I/O?

### ISSUE THREAD

**Issue by yuanman1988** [tttapa/Control-Surface#61]
Hello Pieter!
I have a question about Multiplexers 4067.
I read your example,and success for one Multiplexers 4067 . But I don't know how to use two or three or more than Multiplexers 4067 to expand the I/O. Can you give me some help?
Thank you.

![image](https://user-images.githubusercontent.com/56752742/69249028-3b187c00-0be8-11ea-9d97-8f5a1c1e80cf.png)

**Comment by shikshik** [comment]
You need to connect each mux to it's EN pin on your Arduino.

`mux1 = {
2,
{3, 4, 5, 6},
7
};`

`mux1 = {
2,
{3, 4, 5, 6},
8
};`

**Comment by tttapa** [comment]
What exactly would you like help with?  
The code looks fine, both muxes share the same address lines, and each one has its own input pin.  

In the rest of your code, you can just use the pins of both multiplexers, for example:

```cpp
NoteButton notebuttons[] = {
  {mux1.pin(0), 0x3C}, // first pin of first mux
  {mux2.pin(0), 0x3D}, // first pin of second mux
};
```

**Comment by yuanman1988** [comment]
Oh no！
I forgot to delete or modify  the “loop2” in your example,
It led to error...
I'm an idiot.
Now,it runs good.
Anyway, thanks for your reply.And thanks  for your library.It's so cool.

**Comment by yuanman1988** [comment]
![image](https://user-images.githubusercontent.com/56752742/69305710-e3b5f280-0c5f-11ea-86d0-0f44ec27c98a.png)
![image](https://user-images.githubusercontent.com/56752742/69305728-f4666880-0c5f-11ea-84e4-5dd9f7684bce.png)
![image](https://user-images.githubusercontent.com/56752742/69305780-28da2480-0c60-11ea-9943-0f70fb962b1f.png)
cool (๑•̀ㅂ•́)و✧

**Comment by yuanman1988** [comment]
I have another question.

![image](https://user-images.githubusercontent.com/56752742/69344944-3668cc00-0cab-11ea-99e1-3ad9851ed26d.png)



What should I do same as “usbMIDI.sendNoteOn(3C, velocity, Channel)” .

**Comment by tttapa** [comment]
The signature of the NoteButton constructor is as follows: <https://tttapa.github.io/Control-Surface/Doc/Doxygen/d1/d9f/classNoteButton.html#a42d82a21f570f194515c9a7c594c5601>

For example:
```cpp
const uint8_t velocity = 0x7F;
NoteButton buttons[] = {
  {mux1.pin(0), {0x3C, CHANNEL_6}, velocity},
  {mux1.pin(0), {0x3C, CHANNEL_7}, velocity},
};
```
You can also set the velocity afterwards:
```cpp
buttons[0].setVelocity(0x40);
```

**Comment by yuanman1988** [comment]
Oh, I see.I need more study.
 I'll try to do it.
Thank you for your help.
