### ISSUE TITLE
send ppqn via usb

### ISSUE THREAD

**Issue by 2kohm** [tttapa/Control-Surface#63]
hi,
is it possible to send 

- // Clock start = 0xFA
- // Clock stop = 0xFC
- // Clock pulse = 0xF8

via USB with this library ?

**Comment by tttapa** [comment]
Yes, I just added it in 461a67fee2065d7669cdcdb5aa5f75e430070691.

```cpp
#include <Control_Surface.h>

// Instantiate the MIDI over USB interface
USBMIDI_Interface midi;

// Push button connected between pin 2 and ground.
// MIDI Clock message is sent when pressed.
Button pushbutton = {2};  

void setup() {
  pushbutton.begin();  // enables internal pull-up
  midi.begin();
}

void loop() {
  if (pushbutton.update() == Button::Falling)
    midi.send(0xF8);
  midi.update();
}
```

**Comment by 2kohm** [comment]
awesome, thanks for the fast replay and adding this!!!!

**Comment by 2kohm** [comment]
mh

`Arduino\libraries\Control-Surface-master\src/MIDI_Inputs/MCU/VU.hpp:90:16: warning: missing initializer for member 'Array<unsigned char, 1u>::data' [-Wmissing-field-initializers]

         values = {};

                ^`
