### ISSUE TITLE
send note on / off on events

### ISSUE THREAD

**Issue by 2kohm** [tttapa/Control-Surface#65]
First, thanks again for the arduino due fix
i am working on a usbmidi send clock.

works perfect so far.

is it possible to send note on and off events like with the MIDIUSB lib 

`void noteOn(byte channel, byte pitch, byte velocity) {
  midiEventPacket_t noteOn = {0x09, 0x90 | channel, pitch, velocity};
  MidiUSB.sendMIDI(noteOn);
}`

`void noteOff(byte channel, byte pitch, byte velocity) {
  midiEventPacket_t noteOff = {0x08, 0x80 | channel, pitch, velocity};
  MidiUSB.sendMIDI(noteOff);
}`

with your lib ? since it is bounded to button presses in your lib

` if (something) {
noteOn(0,60,127);
}
`

if i combine MIDIUSB to send note events, and send clock pulses with your lib i'll get strange behavior

**Comment by tttapa** [comment]
You can use the `sendNoteOn` method of the MIDI_Interface class: https://tttapa.github.io/Control-Surface/Doc/Doxygen/d9/d73/classMIDI__Interface.html#a80c4843f88185a213ebe20a26c0fd579

The channel and cable number are optional. If you only specify the note number, you don't need braces.

For example:
```cpp
USBMIDI_Interface midi;

[...]

midi.sendNoteOn({0x3C, CHANNEL_3, 10}, 0x7F); // Note 0x3C (middle C), Channel 3, Cable 10, Velocity 0x7F
midi.sendNoteOn({0x3C, CHANNEL_3}, 0x7F);     // Cable 0 (first and default cable)
midi.sendNoteOn(0x3C, 0x7F);                  // Channel 1, Cable 0
```

**Comment by tttapa** [comment]
But you only need that if you manually have to send the note events.

If you want a button or switch that sends MIDI note events when pressed, you can use the [NoteButton](https://tttapa.github.io/Control-Surface/Doc/Doxygen/de/dcc/NoteButton_8ino-example.html) class.

**Comment by 2kohm** [comment]
thanks again for your fast replay! clock generation on the due works perfect with 96 ppqn resolution!

another question :D 

how would i do 
`  midiEventPacket_t rx;
  do {
    rx = MidiUSB.read();
    if (rx.header != 0) {
      Serial.print("Received: ");
      Serial.print(rx.header, HEX);
      Serial.print("-");
      Serial.print(rx.byte1, HEX);
      Serial.print("-");
      Serial.print(rx.byte2, HEX);
      Serial.print("-");
      Serial.println(rx.byte3, HEX);
    }
  } while (rx.header != 0);`
with your lib ? i wan't to read incoming clock signals

**Comment by tttapa** [comment]
Glad to hear!

You can add custom callbacks to the MIDI inputs: https://tttapa.github.io/Control-Surface/Doc/Doxygen/d0/d32/MIDI-Input-Callback_8ino-example.html

**Comment by 2kohm** [comment]
ok, this works fine, `Real-Time message: f8 on cable 0`
but how can grab this clock event ?

```
if (serial.read == 0xf8) {
};
```

**Comment by tttapa** [comment]
You can add your own code in the `realTimeMessageCallback` function, and then use [`rt.message`](https://tttapa.github.io/Control-Surface/Doc/Doxygen/d6/d99/structRealTimeMessage.html).

```cpp
bool realTimeMessageCallback(RealTimeMessage rt) {
  if (rt.message == 0xF8) {
    // Do what you need to do if a clock event is received
  }
  return true;
}
```
