### ISSUE TITLE
Bug on Multiplexer in DUE

### ISSUE THREAD

**Issue by nickho74** [tttapa/Control-Surface#706]
Arduino DUE - Upload sketch in v1.2.0
1.  When button pressed in Mux pin(0) = Mux pin(0) & Mux pin(8) outputting at the same time.
2.  When button pressed in Mux pin(8) = Mux pin(0) & Mux pin(8) outputting at the same time.
3. The rest of the 14 buttons when pressed function as it is.
4. Mux on Potentiometer is working correctly.

Arduino DUE - Upload sketch back to older version v1.1.1
1.  When button pressed for Mux pin(0) = Mux pin(0) is outputting correctly.
2.  When button pressed for Mux pin(8) = Mux pin(8) is outputting correctly.
3. The rest of the 14 buttons when pressed function as it is.
4. Mux on Potentiometer is working correctly.

Also tested both version for Arduino Mega.
1. Multiplexer working normally for both version.

Please advise on the bug report.

#include <Control_Surface.h>  // Include the library

USBMIDI_Interface midiusb;
HardwareSerialMIDI_Interface midiserial1 {Serial1, MIDI_BAUD};

// Instantiate an analog multiplexer
CD74HC4067 mux1 = {  8, { 2, 3, 4, 5 } }; // Multiplexer 1, 16 Button
CD74HC4067 mux2 = { A0, { 2, 3, 4, 5 } }; // Multiplexer 4, 16 Fader

// Instantiate a NoteButton object
NoteButton button [] {
  { mux1.pin(0),  {  1, CHANNEL_1 } },
  { mux1.pin(1),  {  2, CHANNEL_1 } },
  { mux1.pin(2),  {  3, CHANNEL_1 } },
  { mux1.pin(3),  {  4, CHANNEL_1 } },
  { mux1.pin(4),  {  5, CHANNEL_1 } },
  { mux1.pin(5),  {  6, CHANNEL_1 } },
  { mux1.pin(6),  {  7, CHANNEL_1 } },
  { mux1.pin(7),  {  8, CHANNEL_1 } },
  { mux1.pin(8),  {  9, CHANNEL_1 } },
  { mux1.pin(9),  { 10, CHANNEL_1 } },
  { mux1.pin(10), { 11, CHANNEL_1 } },
  { mux1.pin(11), { 12, CHANNEL_1 } },
  { mux1.pin(12), { 13, CHANNEL_1 } },
  { mux1.pin(13), { 14, CHANNEL_1 } },
  { mux1.pin(14), { 15, CHANNEL_1 } },
  { mux1.pin(15), { 16, CHANNEL_1 } },
};

// Create an array of CCPotentiometer objects that send out MIDI Control Change 
// messages when you turn the potentiometers connected to the 8 inputs of the mux.
CCPotentiometer volumePotentiometers[] {
  { mux2.pin(0),  { MIDI_CC::Channel_Volume, CHANNEL_1  } },
  { mux2.pin(1),  { MIDI_CC::Channel_Volume, CHANNEL_2  } },
  { mux2.pin(2),  { MIDI_CC::Channel_Volume, CHANNEL_3  } },
  { mux2.pin(3),  { MIDI_CC::Channel_Volume, CHANNEL_4  } },
  { mux2.pin(4),  { MIDI_CC::Channel_Volume, CHANNEL_5  } },
  { mux2.pin(5),  { MIDI_CC::Channel_Volume, CHANNEL_6  } },
  { mux2.pin(6),  { MIDI_CC::Channel_Volume, CHANNEL_7  } },
  { mux2.pin(7),  { MIDI_CC::Channel_Volume, CHANNEL_8  } },
  { mux2.pin(8),  { MIDI_CC::Channel_Volume, CHANNEL_9  } },
  { mux2.pin(9),  { MIDI_CC::Channel_Volume, CHANNEL_10 } },
  { mux2.pin(10), { MIDI_CC::Channel_Volume, CHANNEL_11 } },
  { mux2.pin(11), { MIDI_CC::Channel_Volume, CHANNEL_12 } },
  { mux2.pin(12), { MIDI_CC::Channel_Volume, CHANNEL_13 } },
  { mux2.pin(13), { MIDI_CC::Channel_Volume, CHANNEL_14 } },
  { mux2.pin(14), { MIDI_CC::Channel_Volume, CHANNEL_15 } },
  { mux2.pin(15), { MIDI_CC::Channel_Volume, CHANNEL_16 } },
};
 
void setup() {
  Control_Surface.begin();  // Initialize the Control Surface
}
 
void loop() {
  Control_Surface.loop();  // Update the Control Surface
}

**Comment by tttapa** [comment]
You could try increasing this delay: 

https://github.com/tttapa/Control-Surface/blob/e36305d131a7cff7d43c77d7655cf12090ed4402/src/AH/Hardware/ExtendedInputOutput/AnalogMultiplex.hpp#L246

**Comment by nickho74** [comment]
ok got it. I have modify the timing to 5. It is now all working ! 

Thank you !
