### ISSUE TITLE
Do you have schematic for midi 5 pin with node mcu v3 (8266)?

### ISSUE THREAD

**Issue by e36910** [tttapa/Control-Surface#761]
How to solder midi 5 pin to arduino?

**Comment by e36910** [comment]
I found this pattern. Does she fit that project? If suitable, which pin on the Arduino 8266 board to use for midi data? 
![IMG_20220616_083234](https://user-images.githubusercontent.com/85799952/173999194-a8408d58-71d6-4520-a19e-840f3a99efb2.jpg)

**Comment by tttapa** [comment]
No, the only officially correct schematic is the one I posted a link to earlier.

The pin you should use for the output is the UART TX pin. But as mentioned earlier, you probably want a 5V buffer in between.

**Comment by e36910** [comment]
I don't understand wich pin I need used in my board?
2=GDN
4=R200+Vin
5=R220+TX ?

**Comment by e36910** [comment]
This is correct schematic for midi 5 pin. In this example we need used - USBMIDI_Interface midi;
It does work.
