### ISSUE TITLE
Manual CC number in contructor for CCPotentiometer

### ISSUE THREAD

**Issue by koraysels** [tttapa/Control-Surface#78]
Hi, maybe i cannot sse it but I want my slider pot to control cc parameter 42.. How can I achieve this? I only see general purpose midi names here in [`Control__Change_.hpp`](https://tttapa.github.io/Control-Surface-doc/Doxygen/d9/d43/Control__Change_8hpp_source.html) 

If i canvert 42 to hex it is 0x2A .. But if I put that in the contructor and i inspect it with midi monitor it turns out it controls the PAN parameter... .

**Comment by tttapa** [comment]
You don't have to use the constants, you can just use "42":

```cpp
CCPotentiometer potentiometer = {
  A0,
  {42, CHANNEL_1},
};
```

The reason that the MIDI monitor displays "Pan" is because controller 42 is defined as the least significant byte of the pan control by the MIDI standard. Most modern DAWs do not follow these mappings.
