### ISSUE TITLE
Reading a CC value to ShiftReg Vu-Meter

### ISSUE THREAD

**Issue by hachimbala** [tttapa/Control-Surface#9]
Hello, I want to read a CC value send from Traktor( for example the CC 004 of the channel 3) with a range from 0 to 127 and according to the value, light 8 leds increasingly like a VU-Meter.

I have searched and I only have found in the examples some banks and in the example of the ShiftReg LEDs that it light up all the LEDs, but it doesn0t read the CC value and according to that, make the VUMeter effect.
So, how can I do that?
Thank you so much
Best regards

**Comment by masydoblig** [comment]
This would be what i might need to get the vu meter working from the generic controller in cubase 

The CC value meter
