### ISSUE TITLE
Error Compiling

### ISSUE THREAD

**Issue by arthurbrazil** [tttapa/Control-Surface#96]
Arduino: 1.8.9 (Windows Store 1.8.21.0) (Windows 10), Board: "Arduino/Genuino Mega or Mega 2560, ATmega2560 (Mega 2560)"

C:\Users\Arthur\Documents\Arduino\libraries\Control-Surface-master\src\MIDI_Interfaces\MIDI_Interface.cpp: In member function 'sinkMIDIfromPipe':

C:\Users\Arthur\Documents\Arduino\libraries\Control-Surface-master\src\MIDI_Interfaces\MIDI_Interface.cpp:134:70: internal compiler error: Segmentation fault

 void MIDI_Interface::sinkMIDIfromPipe(SysExMessage msg) { send(msg); }

                                                                      ^

Please submit a full bug report,

with preprocessed source if appropriate.

See <http://gcc.gnu.org/bugs.html> for instructions.

lto-wrapper.exe: fatal error: C:\Program Files\WindowsApps\ArduinoLLC.ArduinoIDE_1.8.21.0_x86__mdqgnx93n4wtt\hardware\tools\avr/bin/avr-gcc returned 1 exit status

compilation terminated.

c:/program files/windowsapps/arduinollc.arduinoide_1.8.21.0_x86__mdqgnx93n4wtt/hardware/tools/avr/bin/../lib/gcc/avr/5.4.0/../../../../avr/bin/ld.exe: error: lto-wrapper failed

collect2.exe: error: ld returned 1 exit status

exit status 1
Error compiling for board Arduino/Genuino Mega or Mega 2560.

This report would have more information with
"Show verbose output during compilation"
option enabled in File -> Preferences.

Any idea what would be causing this?

**Comment by tttapa** [comment]
This is an internal compiler error, it's a bug in the compiler, not in the library.  
There's nothing I can do about it. You could try using the Arduino IDE from the official website instead of the one from the Windows store.

If that doesn't work, try the previous release of the library instead of the `master` version: https://github.com/tttapa/Control-Surface/releases
