### ISSUE TITLE
debug incoming midi messages

### ISSUE THREAD

**Issue by LukaszChrzanowski** [tttapa/Control-Surface#98]
How can I get to send incoming midi messages from MIDI Interface to Serial port?

tried:
void setup() {
Serial.begin(115200);
  while (!Serial)
    ;
  Control_Surface.begin(); // Initialize Control Surface
}
void loop() {
  Control_Surface.loop(); // Update the Control Surface
DEBUGVAL(Serial.read());
}
but it looks that it doesn't work

**Comment by tttapa** [comment]
You can attach callbacks for the MIDI events you want to debug:  
<https://tttapa.github.io/Control-Surface-doc/Doxygen/d0/d32/MIDI-Input-Callback_8ino-example.html>

**Comment by LukaszChrzanowski** [comment]
this resolved my problem.
Thank You.

Thread for close
